### ISSUE TITLE
Android-support-v4.jar mismatch with facebookConnect

### ISSUE THREAD

**Issue by Omnem** [one-signal/OneSignal-Cordova-SDK#2] opened 2015-06-30 10:29 UTC
The moment I've added the OneSignal plugin, the build for Android failed with the following error:
```
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /project/com.phonegap.plugins.facebookconnect/cyberdunk-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /project/libs/android-support-v4.jar
[dependency] 	Length: 987314
[dependency] 	SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies
```
It seems the facebookConnect plugin and this one are using different android libraries.

Is there a known fix ? Any 2 versions of the two plugins are compatible ? Any thoughts ? It seems to build on iOS.

Thank you

**Comment by jkasten2** [comment] 2015-06-30 22:40
Hello,

Unfortunately the [Official Facebook Cordova plugin](https://github.com/Wizcorp/phonegap-facebook-plugin) includes the android-support-v4.jar bundle instead of externally defining it as a dependency as OneSignal does. See their [open issue #750](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/750).

As a work around for now you can delete `<project-root>\platforms\android\libs\android-support-v4.jar`.

Thanks.

**Comment by Omnem** [comment] 2015-07-03 13:03
I was using the PhoneGap Build Service so I was unable to implement your fix right away. 

After installing the local toolset, your solution worked and I was able to build locally.

Thank you @jkasten2 .

**Comment by jkasten2** [comment] 2015-07-09 04:49
We just added our plugin to [npmjs](https://www.npmjs.com/package/onesignal-cordova-plugin) and updated it to use gradle to handle dependencies but it did not fix this issue with the official fork.

However, there is a fork of the official plugin [cordova-plugin-facebook4](https://www.npmjs.com/package/cordova-plugin-facebook4) that builds just fine with our [onesignal-cordova-plugin](https://www.npmjs.com/package/onesignal-cordova-plugin).

Let us know if it works for you.

Thanks.

**Comment by Omnem** [comment] 2015-07-10 15:36
Using the PhoneGap Build Service. I'm getting this:

"Error - Plugin error (you probably need to remove plugin files from your app): npm http GET https://registry.npmjs.org/cordova-plugin-facebook4 npm http 200 https://registry.npmjs.org/cordova-plugin-facebook4 Failed to install 'cordova-plugin-facebook4':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.6.3, failed version requirement: >=4.0.0-dev at checkEngines "

Haven't checked locally since the previous fixe worked well for me.

I'll google around to see if I can find an available solution.

**Comment by jkasten2** [comment] 2015-07-11 03:41
I just tested cordova-plugin-facebook4 with our onesignal-cordova-plugin locally with Cordova CLI. Since PhoneGap Build(PGB) lets you use Cordova 5.1.1 I didn't think it would be an issue. However you're right, this doesn't work on PGB as it still uses Ant instead of Gradle. I also seen they have [a blog](http://phonegap.com/blog/2015/06/16/phonegap-updated-on-build/) post on this issue. Thanks for digging in and reporting back your findings.

I'll keep my eye on news from PhoneGap and post here again when I can confirm the issue is fixed for PhoneGap Build as well.

Thanks.

**Comment by jkasten2** [comment] 2015-08-06 03:01
We just released a PhoneGap Build compatibility version that removes the linked dependencies. This fixes all conflict issues with other plugins that use Google Play services or Android Support library v4 or v13 like the facebook plugin.

For Adobe PhoneGap Build users using com.phonegap.plugins.facebookconnect and OneSignal, include the following your config.xml file instead of "com.onesignal.plugins.onesignal":
```xml
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="com.google.playservices" source="npm" />
```

Let us know if this fixes your PhoneGap build problem and I'll close this github issue.

For all other forks of Cordova using gradle builds (CLI, PhoneGap CLI, Intel XDK, Ionic, etc) we recommend using cordova-plugin-facebook4 and onesignal-cordova-plugin.

Thanks.

**Comment by ichaiwut** [comment] 2015-08-06 07:46
@jkasten2  work for me on `Cordova 5.0.0`

**Comment by k-cgomezh** [comment] 2015-08-12 17:11
what is the right sentence on config.xml   for  the facebook connect plugin ??

**Comment by jkasten2** [comment] 2015-08-12 19:24
For PhoneGap Build it looks like to include the facebook connect plugin you add the following to your `config.xml`:
```xml
<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0">
    <param name="APP_ID" value="..." />
    <param name="APP_NAME" value="..." />
</gap:plugin>
```

Their [facebook connect plugin on PhoneGap Build](https://build.phonegap.com/plugins/1246) is at 0.9.0 but the latest is 0.11.0. If there are any import bug fixes or features in the missing versions I would recommend you create an issue on their [github repo](https://github.com/Wizcorp/phonegap-facebook-plugin).

Thanks.

**Comment by Omnem** [comment] 2015-08-14 12:15
Excellent work @jkasten2 . Just in time for our release.
The following combo has worked perfectly with the PhoneGap Build:

```
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="com.google.playservices" source="npm" />

<gap:plugin name="com.phonegap.plugins.facebookconnect" version="0.9.0"> 
        <param name="APP_ID" value="..." />
        <param name="APP_NAME" value="..." />
    </gap:plugin>    
```
with  

```
<preference name='phonegap-version' value='cli-5.1.1' />
```

Haven't tested with my previously used version 3.6.3.

Thank you, 
Unbeatable service.
Feel free to close this.


P.S. 
A small unrelated noted to anyone upgrading from phonegap build 3.6.3 or earlier to cli-5.1.1.
You'll have to switch previously used core plugins to use NPM:

```
 <gap:plugin name="org.apache.cordova.inappbrowser" version="0.5.2" />
```
to
```
<gap:plugin name="cordova-plugin-inappbrowser" source="npm" />
```

--> http://community.phonegap.com/nitobi/topics/andoird-build-failing-on-new-version-5-1-1

**Closed** 2015-08-14 12:42 UTC

**Comment by k-cgomezh** [comment] 2015-08-17 06:20
We still have the same issue. We can't remove Android-support-v4.jar because we are building with PBG. We tried using source="npm" but it didnt' work. We tried with:

<preference name='phonegap-version' value='cli-5.1.1' />

But it didn't work either. 

Btw, our issue is with Local Notification plugin  <gap:plugin name="de.appplant.cordova.plugin.local-notification"/>  when building we get the same message:  

clean:
[dependency] 
[dependency] ------------------
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /project/com.phonegap.plugins.facebookconnect/XXXXXX-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /project/libs/android-support-v4.jar
[dependency] 	Length: 19036
[dependency] 	SHA-1: bc202617b4cfed6673b1e10d87e52c78f7a6de38

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies

**Comment by Omnem** [comment] 2015-08-17 08:12
Might be useful if you could post the config.xml @k-cgomezh 
Which oneSignal plugin are you using ?

Make sure you use this
```
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="com.google.playservices" source="npm" />
```

Instead of this

```
<gap:plugin name="com.onesignal.plugins.onesignal"   /> 
```

They are different plugins, in the sense that they load that file differently from my understanding.

**Comment by k-cgomezh** [comment] 2015-08-18 06:38
we are not using oneSignal. As I said we are unable to use these plugins together:

com.phonegap.plugins.facebookconnect
de.appplant.cordova.plugin.local-notification
